image: docker

stages:
  - test

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker-compose version

test:
  stage: test
  script:
    - docker-compose -f compose/test/docker-compose.test.yml build
    - docker-compose -f compose/test/docker-compose.test.yml run test coverage run --source='.' manage.py test --keepdb
    - docker-compose -f compose/test/docker-compose.test.yml run test coverage report
