version: '3'

services:
  db:
    image: postgres:10
    restart: always
    volumes:
      - db_dev_volume:/var/lib/postgresql

  dev:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MODE_ENVIROMENT: dev

volumes:
  db_dev_volume:
